services:
  multimeet:
    container_name: multimeet
    image: multimeet:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - NC_PORT=8080
      - DB_NC_URL=jdbc:postgresql://multimeet_db:5432/multimeet
      - DB_NC_USERNAME=nc18-40
      - DB_NC_PASSWORD=nc18-40pwd
    depends_on:
      - multimeet_db
  multimeet_db:
    image: postgres:14.12
    container_name: multimeet_db
    restart: always
    environment:
      POSTGRES_DB: multimeet
      POSTGRES_USER: nc18-40
      POSTGRES_PASSWORD: nc18-40pwd
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5433:5432'
